-- by Verdatim 23/5/2026
-- credits to PrivatePirate97 for the guide in the anomaly modding book

class "ValidWeaponSpawner" (CUIScriptWnd)	-- 1

function ValidWeaponSpawner:__init() super() -- 2
	self:InitControls()
end

function ValidWeaponSpawner:InitControls() -- 2
	self:SetWndRect(Frect():set(0,0, 1024, 768)) -- sets corner positions (left, top, right, bottom) of the dialog window
	self:SetAutoDelete(true)
	
	self.xml = CScriptXmlInit()
	local xml = self.xml -- just so you don't have to write 'self.xml' every time
	xml:ParseFile("ValidWeaponSpawner.xml")
	
	self.my_wnd = xml:InitStatic("background", self)
	
	local kinds = {"w_pistol", "w_rifle", "w_shotgun", "w_sniper", "w_smg", "w_explosive", "all"}
	self.buttons = {}
	
	for i = 1,7 do
		local kind = kinds[i]
		self.buttons[kind] = xml:Init3tButton("background:button_" .. kind, self.my_wnd)
		self.buttons[kind]:TextControl():SetText("Spawn " .. kind)
		
		self:Register(self.buttons[kind], "button".. kind)
		
		local _wrapper = function(self)
			self:On_Spawn_Button_Press(kind)
		end
		self:AddCallback("button".. kind, ui_events.BUTTON_DOWN, _wrapper, self)
	end
	
	self.button_clear_inventory = xml:Init3tButton("background:button_clear_inventory", self.my_wnd)
	self.button_clear_inventory:TextControl():SetText("Clear Weapons From Inv")
	self:Register(self.button_clear_inventory, "button_clear_inventory")
	self:AddCallback("button_clear_inventory", ui_events.BUTTON_CLICKED, self.on_button_clear_inventory_press, self)
end

allowed_kinds = {}
allowed_kinds.w_pistol = true
allowed_kinds.w_rifle = true
allowed_kinds.w_shotgun = true
allowed_kinds.w_sniper = true
allowed_kinds.w_smg = true
allowed_kinds.w_explosive = true

function ValidWeaponSpawner:on_button_clear_inventory_press()
	local function iterator(_, itm)
		local kind = ini_sys:r_string_ex(itm:section(), "kind")
		if allowed_kinds[kind] then
			alife_release_id(itm:id())
		end
	end
	db.actor:iterate_inventory(iterator, db.actor)
end

function ValidWeaponSpawner:On_Spawn_Button_Press(param)
	valid_weapons_spawner.spawn_kind(param)
end

function ValidWeaponSpawner:__finalize()	-- 3
	-- your code (optional)
end

function ValidWeaponSpawner:Update()		-- 4
	CUIScriptWnd.Update(self)
	-- your code
end

GUI = nil

function show_ui()
	if GUI == nil then
		GUI = ValidWeaponSpawner() -- calls instance of your GUI class
	end
	
	if GUI and not GUI:IsShown() then -- only show the GUI if it is NOT active yet
		GUI:ShowDialog(true)          -- shows the GUI dialog, mouse cursor appears on screen, all user inputs are passed to the GUI
		Register_UI("ValidWeaponSpawner", "valid_weapons_spawner_ui", GUI)
	end
end

function ValidWeaponSpawner:OnKeyboard(key, keyboard_action)
	if (key == DIK_keys.DIK_NUMPAD4) or (key == DIK_keys.DIK_ESCAPE) and keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		close_ui()
	end
end

function close_ui()
	if GUI and GUI:IsShown() then
		GUI:HideDialog() -- closes GUI dialog, mouse cursor disappears, full control over character regained
		Unregister_UI("ValidWeaponSpawner")
		GUI = nil -- optional, destroys GUI instance
	end
end

function on_key_press(key)
	if key == DIK_keys.DIK_NUMPAD3 then
		show_ui()
	end
end

function on_game_start()
	RegisterScriptCallback("on_key_press", on_key_press)
end

